[package]
name = "test-harness-macro"
version = "0.1.0"
edition = "2021"

description = "Test attribute for ghcid-ng"

publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full"] }
