[book]
authors = [
    "Rebecca Turner",
]
language = "en"
multilingual = false
src = "."
title = "ghciwatch"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/MercuryTechnologies/ghciwatch"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/MercuryTechnologies/ghciwatch/edit/main/docs/{path}"
