---
# This is the main CI workflow, run for PRs and on `main`.

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

name: Continuous integration

jobs:
  checks:
    name: Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Log versions
        run: |
          nix --version

      - name: Wait for garnix to build
        uses: lewagon/wait-on-check-action@v1.3.1
        if: runner.os == 'Linux'
        with:
          ref: ${{ github.ref }}
          check-name: 'package default [x86_64-linux]'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait for garnix to build
        uses: lewagon/wait-on-check-action@v1.3.1
        if: runner.os == 'macOS'
        with:
          ref: ${{ github.ref }}
          check-name: 'package default [aarch64-darwin]'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Check Nix flake
        run: nix --extra-experimental-features 'nix-command flakes' flake check --print-build-logs
