---
name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: nix flake check (${{ matrix.platform.runner }})
    runs-on: ${{ matrix.platform.runner }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: ubuntu-latest
          - runner: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true

      - name: nix flake check
        run: nix flake check --print-build-logs
